name: Release

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Install Dependencies
              run: npm ci

            - name: Build JS
              run: npm run build

            - name: Zip files
              run: zip release.zip ./* -r

            - name: Tar files
              run: tar --exclude='./release.zip' -czf release.tar.gz *

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  generate_release_notes: true
                  files: |
                    release.zip
                    release.tar.gz
